config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'index', to: 'home#index', as: 'index'
  get 'write', to: 'home#write'
  get 'update/:post_id', to: 'home#update', as: 'update'
  get 'destroy/:post_id', to: 'home#destroy', as: 'destroy'
  post 'result', to: 'home#result'
  post 'update_result/:post_id', to: 'home#update_result'
  
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @every_post = Post.all
  end

  def write
  end

  def update
    @update_post = Post.find(params[:post_id])
  end
  
  def update_result
    @title = params[:title]
    @content = params[:content]
    
    @update_post = Post.find(params[:post_id])
    @update_post.title=@title
    @update_post.content = @content
    @update_post.save
  end

  def destroy
    @destroy_post = Post.find(params[:post_id])
    @destroy_post.delete
  end
  
  def result
    @title = params[:title]
    @content = params[:content]
    
    @save_post = Post.new #Post타입의 new title을 만듦
    @save_post.title=@title
    @save_post.content = @content
    @save_post.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/destroy.html.erb
<h1>삭제가 되었습니다.</h1>
<a href="index">
    메인으로가기.
</a>

app/views/home/index.html.erb
<a href="write">
    <button><h1>글쓰러 가기</h1></button>
    </a>
    
<% @every_post.each do |p| %>
    <br>게시물 번호 : <%= p.id%>
    <br>제목 : <%= p.title %>
    <br>내용 : <%= p.content %>
    <br>등록일 : <%= p.created_at %>
    
    <br><%= link_to destroy_path(post_id: p.id) do %>
    <!--ㄴ은 <a href="/destroy/<%=p.id%>">삭제하기</a>  와 같다-->
    <button>
        삭제하기
    </button>
    <% end %>
    
    <%= link_to update_path(p) do %>
    <button>
        수정하기
    </button>
    <% end%>
    
    
    <hr>
<% end %>

app/views/home/result.html.erb
<p>제목 : <%= @title %></p>
<p>내용 : <%= @content%></p>

<br><%= link_to index_path do %>
<!-- a href와의 차이는 link to는 루비 문법임.-->
    <button>메인으로 가기</button>
<% end %>

app/views/home/update.html.erb
<h1>여기는 수정하는 것입니다.</h1>

<form action="/update_result/<%= @update_post.id %>" method="POST"> <!--action="result //result로 글쓴것을 옮겨라--> <!--method = "POST" -->
    <br>제목 : <input type="text" name="title" value="<%= @update_post.title %>">
    <br>내용 : <input type="text" name="content"value="<%= @update_post.content %>">
    
    <br><input type="submit" value="글쓰기"> <!--게시글을 올리는 버튼-->
</form>

app/views/home/update_result.html.erb
<h1>수정이 완료되었습니다.</h1>
<p>제목 : <%= @title %></p>
<p>내용 : <%= @content%></p>

<br><%= link_to index_path do %>
<!-- a href와의 차이는 link to는 루비 문법임.-->
    <button>메인으로 가기</button>
<% end %>

app/views/home/write.html.erb
<h1>여기는 게시판. 글쓰는 곳입니다.</h1>

<form action="result" method="POST"> <!--action="result //result로 글쓴것을 옮겨라--> <!--method = "POST" -->
    <br>제목 : <input type="text" name="title">
    <br>내용 : <input type="text" name="content">
    
    <br><input type="submit" value="글쓰기"> <!--게시글을 올리는 버튼-->
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>